default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: slowfood_api_team_one_development

test:
  <<: *default
  database: slowfood_api_team_one_test

production:
  <<: *default
  database: slowfood_api_team_one__production
  username: slowfood_api
  password: <%= ENV['SLOWFOOD_API_DATABASE_PASSWORD'] %>
